#!/usr/bin/env python3
"""Run the ontology build, enrichment, semantic export, and validation pipeline."""

from __future__ import annotations

import argparse
import subprocess
from pathlib import Path


def run_step(repo_root: Path, args: list[str]) -> None:
    subprocess.run(args, cwd=repo_root, check=True)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--repo-root", default=".")
    parser.add_argument("--validation-date", default="2026-03-14")
    args = parser.parse_args()

    repo_root = Path(args.repo_root).resolve()
    paragraph_source_report = f"qa/ontology/{args.validation_date}_paragraph-source-map-report.json"
    validation_report = f"qa/ontology/{args.validation_date}_ontology-store-validation.json"
    technology_lens_report = f"qa/ontology/{args.validation_date}_technology-lens-validation.json"
    preseed_technology_lens_json = f"qa/ontology/{args.validation_date}_technology-lens-preseed.json"
    preseed_curation_queue_csv = f"qa/ontology/review_queues/{args.validation_date}_technology-lens-curation-preseed.csv"
    preseed_curation_queue_summary = f"qa/ontology/review_queues/{args.validation_date}_technology-lens-curation-preseed-summary.json"
    seed_apply_summary = f"qa/ontology/{args.validation_date}_technology-lens-seed-apply-summary.json"
    postseed_technology_lens_json = f"qa/ontology/{args.validation_date}_technology-lens-postseed.json"
    postseed_curation_queue_csv = f"qa/ontology/review_queues/{args.validation_date}_technology-lens-curation-postseed.csv"
    postseed_curation_queue_summary = f"qa/ontology/review_queues/{args.validation_date}_technology-lens-curation-postseed-summary.json"
    expand_apply_summary = f"qa/ontology/{args.validation_date}_technology-lens-expand-apply-summary.json"
    decision_csv = repo_root / "qa/ontology/review_queues/policy-item-strategy-review-decisions.csv"
    batch_dir = repo_root / "qa/ontology/review_packets/strategy_batches"
    review_workbench_dir = repo_root / "work/04_ontology/review_workbenches"
    reviewed_items_dir = repo_root / "work/04_ontology/reviewed_items"

    run_step(
        repo_root,
        [
            "python3",
            "scripts/run_phase1_policy_normalization_batch.py",
            "--out-root",
            ".",
        ],
    )
    run_step(
        repo_root,
        [
            "python3",
            "scripts/build_policy_ontology_seeds.py",
            "--registry-path",
            "work/01_scope-and-ia/requirements/04_document-registry.csv",
            "--out-dir",
            "work/04_ontology/instances",
        ],
    )
    run_step(
        repo_root,
        [
            "python3",
            "scripts/build_strategy_seeds.py",
            "--out-dir",
            "work/04_ontology/instances",
        ],
    )
    run_step(
        repo_root,
        [
            "python3",
            "scripts/init_ontology_store.py",
            "--db-path",
            "work/04_ontology/ontology.sqlite",
            "--schema-path",
            "work/04_ontology/schemas/03_relational-ontology-schema.sql",
            "--seed-dir",
            "work/04_ontology/instances",
            "--replace",
        ],
    )
    run_step(
        repo_root,
        [
            "python3",
            "scripts/load_ontology_evidence.py",
            "--db-path",
            "work/04_ontology/ontology.sqlite",
            "--normalized-dir",
            "work/03_processing/normalized",
            "--instances-dir",
            "work/04_ontology/instances",
            "--figures-dir",
            "work/02_structured-extraction/figures",
        ],
    )
    run_step(
        repo_root,
        [
            "python3",
            "scripts/build_paragraph_source_map.py",
            "--normalized-dir",
            "work/03_processing/normalized",
            "--text-dir",
            "work/02_structured-extraction/text",
            "--out-csv",
            "work/04_ontology/instances/paragraph_source_map.csv",
            "--out-report",
            paragraph_source_report,
            "--db-path",
            "work/04_ontology/ontology.sqlite",
        ],
    )
    run_step(
        repo_root,
        [
            "python3",
            "scripts/build_source_assets.py",
            "--db-path",
            "work/04_ontology/ontology.sqlite",
            "--repo-root",
            ".",
            "--out-assets-csv",
            "work/04_ontology/instances/source_assets_auto.csv",
            "--out-map-csv",
            "work/04_ontology/instances/derived_to_source_asset_map_auto.csv",
        ],
    )
    run_step(
        repo_root,
        [
            "python3",
            "scripts/build_tech_taxonomy_seeds.py",
            "--taxonomy-csv",
            "work/03_processing/normalized/DOC-TAX-001__tech-domain-subdomain.csv",
            "--out-dir",
            "work/04_ontology/instances",
            "--db-path",
            "work/04_ontology/ontology.sqlite",
        ],
    )
    run_step(
        repo_root,
        [
            "python3",
            "scripts/build_strategy_seeds.py",
            "--out-dir",
            "work/04_ontology/instances",
            "--db-path",
            "work/04_ontology/ontology.sqlite",
        ],
    )
    run_step(
        repo_root,
        [
            "python3",
            "scripts/build_strategy_alignment_exceptions.py",
            "--out-dir",
            "work/04_ontology/instances",
        ],
    )
    run_step(
        repo_root,
        [
            "python3",
            "scripts/build_auto_policy_items.py",
            "--db-path",
            "work/04_ontology/ontology.sqlite",
            "--out-dir",
            "work/04_ontology/instances",
        ],
    )
    if review_workbench_dir.exists():
        run_step(
            repo_root,
            [
                "python3",
                "scripts/run_phase1_reviewed_policy_item_export_batch.py",
                "--out-root",
                ".",
                "--run-date",
                args.validation_date,
            ],
        )
        run_step(
            repo_root,
            [
                "python3",
                "scripts/load_reviewed_policy_items.py",
                "--db-path",
                "work/04_ontology/ontology.sqlite",
                "--reviewed-items-dir",
                "work/04_ontology/reviewed_items",
                "--out-summary-json",
                f"work/04_ontology/reviewed_items/batch_runs/{args.validation_date}_phase1-reviewed-policy-item-load-batch.json",
                "--out-summary-csv",
                f"work/04_ontology/reviewed_items/batch_runs/{args.validation_date}_phase1-reviewed-policy-item-load-batch.csv",
            ],
        )
    run_step(
        repo_root,
        [
            "python3",
            "scripts/classify_policy_items_tech_domains.py",
            "--db-path",
            "work/04_ontology/ontology.sqlite",
            "--keyword-json",
            "work/04_ontology/vocabularies/tech-domain-keywords.json",
            "--out-csv",
            "work/04_ontology/instances/policy_item_taxonomy_map_auto.csv",
        ],
    )
    run_step(
        repo_root,
        [
            "python3",
            "scripts/classify_policy_items_strategies.py",
            "--db-path",
            "work/04_ontology/ontology.sqlite",
            "--keyword-json",
            "work/04_ontology/vocabularies/strategy-keywords.json",
            "--out-csv",
            "work/04_ontology/instances/policy_item_strategy_map_auto.csv",
            "--alignment-exceptions-csv",
            "work/04_ontology/instances/strategy_alignment_exceptions.csv",
        ],
    )
    if decision_csv.exists() and batch_dir.exists():
        run_step(
            repo_root,
            [
                "python3",
                "scripts/merge_strategy_review_batches.py",
                "--decision-csv",
                "qa/ontology/review_queues/policy-item-strategy-review-decisions.csv",
                "--batches-dir",
                "qa/ontology/review_packets/strategy_batches",
                "--out-summary-json",
                "qa/ontology/reviewed_queues/policy-item-strategy-review-batch-merge-summary.json",
            ],
        )
    if decision_csv.exists():
        run_step(
            repo_root,
            [
                "python3",
                "scripts/apply_strategy_review_decisions.py",
                "--db-path",
                "work/04_ontology/ontology.sqlite",
                "--decision-csv",
                "qa/ontology/review_queues/policy-item-strategy-review-decisions.csv",
                "--out-reviewed-map-csv",
                "work/04_ontology/instances/policy_item_strategy_map_reviewed.csv",
                "--out-reviewed-queue-csv",
                "qa/ontology/reviewed_queues/policy-item-strategy-review-reviewed.csv",
                "--out-summary-json",
                "qa/ontology/reviewed_queues/policy-item-strategy-review-reviewed-summary.json",
                "--asserted-at",
                args.validation_date,
            ],
        )
    run_step(
        repo_root,
        [
            "python3",
            "scripts/build_strategy_review_queue.py",
            "--db-path",
            "work/04_ontology/ontology.sqlite",
            "--keyword-json",
            "work/04_ontology/vocabularies/strategy-keywords.json",
            "--out-csv",
            "qa/ontology/review_queues/policy-item-strategy-review-queue.csv",
            "--out-summary-json",
            "qa/ontology/review_queues/policy-item-strategy-review-queue-summary.json",
            "--alignment-exceptions-csv",
            "work/04_ontology/instances/strategy_alignment_exceptions.csv",
        ],
    )
    run_step(
        repo_root,
        [
            "python3",
            "scripts/sync_strategy_review_decisions.py",
            "--queue-csv",
            "qa/ontology/review_queues/policy-item-strategy-review-queue.csv",
            "--out-decision-csv",
            "qa/ontology/review_queues/policy-item-strategy-review-decisions.csv",
            "--out-summary-json",
            "qa/ontology/review_queues/policy-item-strategy-review-decisions-summary.json",
            "--auto-seed-policy-ids",
            "POL-001,POL-007,POL-008,POL-009,POL-010,POL-012",
            "--require-tech-domains-for-auto-review-policy-ids",
            "POL-001",
        ],
    )
    if decision_csv.exists():
        run_step(
            repo_root,
            [
                "python3",
                "scripts/apply_strategy_review_decisions.py",
                "--db-path",
                "work/04_ontology/ontology.sqlite",
                "--decision-csv",
                "qa/ontology/review_queues/policy-item-strategy-review-decisions.csv",
                "--out-reviewed-map-csv",
                "work/04_ontology/instances/policy_item_strategy_map_reviewed.csv",
                "--out-reviewed-queue-csv",
                "qa/ontology/reviewed_queues/policy-item-strategy-review-reviewed.csv",
                "--out-summary-json",
                "qa/ontology/reviewed_queues/policy-item-strategy-review-reviewed-summary.json",
                "--asserted-at",
                args.validation_date,
            ],
        )
    run_step(
        repo_root,
        [
            "python3",
            "scripts/bootstrap_curated_content_sample_layer.py",
            "--repo-root",
            ".",
            "--db-path",
            "work/04_ontology/ontology.sqlite",
            "--sample-dir",
            "work/04_ontology/sample_build/curated_content_sample",
            "--pack-json",
            "work/04_ontology/sample_build/curated_content_sample/curated_content_sample_pack.json",
            "--summary-json",
            "work/04_ontology/sample_build/curated_content_sample/curated_content_sample_summary.json",
            "--pack-validation-json",
            f"qa/ontology/{args.validation_date}_curated-content-sample-pack-validation.json",
            "--derived-map-csv",
            "work/04_ontology/instances/derived_to_source_asset_map_auto.csv",
            "--source-assets-csv",
            "work/04_ontology/instances/source_assets_auto.csv",
        ],
    )
    run_step(
        repo_root,
        [
            "python3",
            "scripts/export_technology_lens_projection.py",
            "--db-path",
            "work/04_ontology/ontology.sqlite",
            "--out-json",
            preseed_technology_lens_json,
        ],
    )
    run_step(
        repo_root,
        [
            "python3",
            "scripts/build_technology_lens_curation_queue.py",
            "--projection-json",
            preseed_technology_lens_json,
            "--out-csv",
            preseed_curation_queue_csv,
            "--out-summary-json",
            preseed_curation_queue_summary,
        ],
    )
    run_step(
        repo_root,
        [
            "python3",
            "scripts/build_technology_lens_seed_draft_pack.py",
            "--projection-json",
            preseed_technology_lens_json,
            "--queue-csv",
            preseed_curation_queue_csv,
            "--out-dir",
            "qa/ontology/review_drafts/technology_lens_seed_draft_pack",
            "--out-summary-json",
            "qa/ontology/review_drafts/technology_lens_seed_draft_pack/technology-lens-seed-draft-pack-summary.json",
        ],
    )
    run_step(
        repo_root,
        [
            "python3",
            "scripts/apply_technology_lens_seed_draft_pack.py",
            "--db-path",
            "work/04_ontology/ontology.sqlite",
            "--draft-pack-dir",
            "qa/ontology/review_drafts/technology_lens_seed_draft_pack",
            "--out-summary-json",
            seed_apply_summary,
        ],
    )
    run_step(
        repo_root,
        [
            "scripts/export_technology_lens_projection.py",
            "--db-path",
            "work/04_ontology/ontology.sqlite",
            "--out-json",
            postseed_technology_lens_json,
        ],
    )
    run_step(
        repo_root,
        [
            "python3",
            "scripts/build_technology_lens_curation_queue.py",
            "--projection-json",
            postseed_technology_lens_json,
            "--out-csv",
            postseed_curation_queue_csv,
            "--out-summary-json",
            postseed_curation_queue_summary,
        ],
    )
    run_step(
        repo_root,
        [
            "python3",
            "scripts/build_technology_lens_expand_draft_pack.py",
            "--projection-json",
            postseed_technology_lens_json,
            "--queue-csv",
            postseed_curation_queue_csv,
            "--out-dir",
            "qa/ontology/review_drafts/technology_lens_expand_draft_pack",
            "--out-summary-json",
            "qa/ontology/review_drafts/technology_lens_expand_draft_pack/technology-lens-expand-draft-pack-summary.json",
        ],
    )
    run_step(
        repo_root,
        [
            "python3",
            "scripts/apply_technology_lens_seed_draft_pack.py",
            "--db-path",
            "work/04_ontology/ontology.sqlite",
            "--draft-pack-dir",
            "qa/ontology/review_drafts/technology_lens_expand_draft_pack",
            "--out-summary-json",
            expand_apply_summary,
        ],
    )
    run_step(
        repo_root,
        [
            "python3",
            "scripts/export_ontology_semantic_layer.py",
            "--db-path",
            "work/04_ontology/ontology.sqlite",
            "--out-jsonld",
            "work/04_ontology/exports/policy-ontology.jsonld",
            "--out-turtle",
            "work/04_ontology/exports/policy-ontology.ttl",
        ],
    )
    run_step(
        repo_root,
        [
            "python3",
            "scripts/validate_ontology_store.py",
            "--db-path",
            "work/04_ontology/ontology.sqlite",
            "--out-report",
            validation_report,
        ],
    )
    run_step(
        repo_root,
        [
            "python3",
            "scripts/export_technology_lens_projection.py",
            "--db-path",
            "work/04_ontology/ontology.sqlite",
            "--out-json",
            "work/05_dashboard/data-contracts/technology-lens.json",
        ],
    )
    run_step(
        repo_root,
        [
            "python3",
            "scripts/validate_technology_lens_projection.py",
            "--projection-json",
            "work/05_dashboard/data-contracts/technology-lens.json",
            "--out-report",
            technology_lens_report,
        ],
    )
    run_step(
        repo_root,
        [
            "python3",
            "scripts/build_technology_lens_curation_queue.py",
            "--projection-json",
            "work/05_dashboard/data-contracts/technology-lens.json",
            "--out-csv",
            "qa/ontology/review_queues/technology-lens-curation-queue.csv",
            "--out-summary-json",
            "qa/ontology/review_queues/technology-lens-curation-queue-summary.json",
        ],
    )
    run_step(
        repo_root,
        [
            "python3",
            "scripts/build_technology_lens_review_queue.py",
            "--projection-json",
            "work/05_dashboard/data-contracts/technology-lens.json",
            "--out-csv",
            "qa/ontology/review_queues/technology-lens-review-queue.csv",
            "--out-summary-json",
            "qa/ontology/review_queues/technology-lens-review-queue-summary.json",
        ],
    )
    run_step(
        repo_root,
        [
            "python3",
            "scripts/sync_technology_lens_review_decisions.py",
            "--queue-csv",
            "qa/ontology/review_queues/technology-lens-review-queue.csv",
            "--out-decision-csv",
            "qa/ontology/review_queues/technology-lens-review-decisions.csv",
            "--out-summary-json",
            "qa/ontology/review_queues/technology-lens-review-decisions-summary.json",
        ],
    )
    run_step(
        repo_root,
        [
            "python3",
            "scripts/apply_technology_lens_review_decisions.py",
            "--db-path",
            "work/04_ontology/ontology.sqlite",
            "--decision-csv",
            "qa/ontology/review_queues/technology-lens-review-decisions.csv",
            "--out-reviewed-queue-csv",
            "qa/ontology/reviewed_queues/technology-lens-review-reviewed.csv",
            "--out-summary-json",
            "qa/ontology/reviewed_queues/technology-lens-review-reviewed-summary.json",
            "--asserted-at",
            args.validation_date,
        ],
    )
    run_step(
        repo_root,
        [
            "python3",
            "scripts/export_ontology_semantic_layer.py",
            "--db-path",
            "work/04_ontology/ontology.sqlite",
            "--out-jsonld",
            "work/04_ontology/exports/policy-ontology.jsonld",
            "--out-turtle",
            "work/04_ontology/exports/policy-ontology.ttl",
        ],
    )
    run_step(
        repo_root,
        [
            "python3",
            "scripts/validate_ontology_store.py",
            "--db-path",
            "work/04_ontology/ontology.sqlite",
            "--out-report",
            validation_report,
        ],
    )
    run_step(
        repo_root,
        [
            "python3",
            "scripts/export_technology_lens_projection.py",
            "--db-path",
            "work/04_ontology/ontology.sqlite",
            "--out-json",
            "work/05_dashboard/data-contracts/technology-lens.json",
        ],
    )
    run_step(
        repo_root,
        [
            "python3",
            "scripts/validate_technology_lens_projection.py",
            "--projection-json",
            "work/05_dashboard/data-contracts/technology-lens.json",
            "--out-report",
            technology_lens_report,
        ],
    )
    run_step(
        repo_root,
        [
            "python3",
            "scripts/build_technology_lens_curation_queue.py",
            "--projection-json",
            "work/05_dashboard/data-contracts/technology-lens.json",
            "--out-csv",
            "qa/ontology/review_queues/technology-lens-curation-queue.csv",
            "--out-summary-json",
            "qa/ontology/review_queues/technology-lens-curation-queue-summary.json",
        ],
    )
    run_step(
        repo_root,
        [
            "python3",
            "scripts/build_technology_lens_review_queue.py",
            "--projection-json",
            "work/05_dashboard/data-contracts/technology-lens.json",
            "--out-csv",
            "qa/ontology/review_queues/technology-lens-review-queue.csv",
            "--out-summary-json",
            "qa/ontology/review_queues/technology-lens-review-queue-summary.json",
        ],
    )
    run_step(
        repo_root,
        [
            "python3",
            "scripts/sync_technology_lens_review_decisions.py",
            "--queue-csv",
            "qa/ontology/review_queues/technology-lens-review-queue.csv",
            "--out-decision-csv",
            "qa/ontology/review_queues/technology-lens-review-decisions.csv",
            "--out-summary-json",
            "qa/ontology/review_queues/technology-lens-review-decisions-summary.json",
        ],
    )
    run_step(
        repo_root,
        [
            "python3",
            "scripts/build_technology_lens_review_packets.py",
            "--decision-csv",
            "qa/ontology/review_queues/technology-lens-review-decisions.csv",
            "--out-dir",
            "qa/ontology/review_packets/technology_lens_by_domain",
            "--out-index-csv",
            "qa/ontology/review_packets/technology-lens-review-index.csv",
            "--out-summary-json",
            "qa/ontology/review_packets/technology-lens-review-index-summary.json",
        ],
    )
    run_step(
        repo_root,
        [
            "python3",
            "scripts/build_strategy_review_packets.py",
            "--decision-csv",
            "qa/ontology/review_queues/policy-item-strategy-review-decisions.csv",
            "--out-dir",
            "qa/ontology/review_packets/strategy_by_policy",
            "--out-index-csv",
            "qa/ontology/review_packets/strategy-review-policy-index.csv",
            "--out-summary-json",
            "qa/ontology/review_packets/strategy-review-policy-index-summary.json",
        ],
    )
    run_step(
        repo_root,
        [
            "python3",
            "scripts/build_strategy_alignment_exception_packets.py",
            "--exception-csv",
            "work/04_ontology/instances/strategy_alignment_exceptions.csv",
            "--queue-csv",
            "qa/ontology/review_queues/policy-item-strategy-review-queue.csv",
            "--decision-csv",
            "qa/ontology/review_queues/policy-item-strategy-review-decisions.csv",
            "--out-dir",
            "qa/ontology/review_packets/strategy_alignment_exceptions",
            "--out-index-csv",
            "qa/ontology/review_packets/strategy-alignment-exception-index.csv",
            "--out-summary-json",
            "qa/ontology/review_packets/strategy-alignment-exception-index-summary.json",
        ],
    )
    run_step(
        repo_root,
        [
            "python3",
            "scripts/build_strategy_alignment_exception_drafts.py",
            "--packet-index-csv",
            "qa/ontology/review_packets/strategy-alignment-exception-index.csv",
            "--packets-dir",
            "qa/ontology/review_packets/strategy_alignment_exceptions",
            "--out-dir",
            "qa/ontology/review_drafts/strategy_alignment_exceptions",
            "--out-index-csv",
            "qa/ontology/review_drafts/strategy-alignment-exception-draft-index.csv",
            "--out-summary-json",
            "qa/ontology/review_drafts/strategy-alignment-exception-draft-summary.json",
        ],
    )
    run_step(
        repo_root,
        [
            "python3",
            "scripts/build_strategy_review_batches.py",
            "--decision-csv",
            "qa/ontology/review_queues/policy-item-strategy-review-decisions.csv",
            "--queue-csv",
            "qa/ontology/review_queues/policy-item-strategy-review-queue.csv",
            "--out-dir",
            "qa/ontology/review_packets/strategy_batches",
            "--out-index-csv",
            "qa/ontology/review_packets/strategy-review-batch-index.csv",
            "--out-summary-json",
            "qa/ontology/review_packets/strategy-review-batch-index-summary.json",
            "--batch-size",
            "40",
        ],
    )
    run_step(
        repo_root,
        [
            "python3",
            "scripts/build_strategy_review_briefs.py",
            "--batch-index-csv",
            "qa/ontology/review_packets/strategy-review-batch-index.csv",
            "--batches-dir",
            "qa/ontology/review_packets/strategy_batches",
            "--out-dir",
            "qa/ontology/review_packets/strategy_briefs",
            "--out-index-md",
            "qa/ontology/review_packets/strategy-review-batch-briefs.md",
        ],
    )
    run_step(
        repo_root,
        [
            "python3",
            "scripts/build_strategy_review_drafts.py",
            "--repo-root",
            ".",
            "--batches-dir",
            "qa/ontology/review_packets/strategy_batches",
            "--out-dir",
            "qa/ontology/review_drafts/batches",
            "--batch-index-csv",
            "qa/ontology/review_packets/strategy-review-batch-index.csv",
        ],
    )
    run_step(
        repo_root,
        [
            "python3",
            "scripts/build_strategy_review_draft_priority_queue.py",
            "--drafts-dir",
            "qa/ontology/review_drafts/batches",
            "--out-csv",
            "qa/ontology/review_drafts/strategy-review-draft-priority-queue.csv",
            "--out-summary-json",
            "qa/ontology/review_drafts/strategy-review-draft-priority-queue-summary.json",
            "--batch-index-csv",
            "qa/ontology/review_packets/strategy-review-batch-index.csv",
        ],
    )

    print("Ontology enrichment pipeline completed.")


if __name__ == "__main__":
    main()
